services:
  elasticsearch:
    image: dataesr/es_icu:7.12.0
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    healthcheck:
      test: curl -s -f elasticsearch:9200/_cat/health > /dev/null || exit 1
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - plight

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: always
    command: --replSet rs0
    volumes:
      - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb:/data/db
    networks:
      - plight

  server:
    build: ./server
    command: npm start
    restart: always
    environment:
      - ES_NODE=http://elasticsearch:9200
      - ES_PASSWORD=
      - ES_USERNAME=
      - MONGO_URI=mongodb://mongodb:27017
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/app/src
    ports:
      - 3000:3000
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - plight

  client:
    build: ./client
    command: npm start
    restart: always
    volumes:
      - ./client/src:/app/src
    ports:
      - 3001:3001
    networks:
      - plight

networks:
  plight: {}

volumes:
  mongodb:
  elastic:
